#if !canImport(ObjectiveC)
  import XCTest

  extension EggSeedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EggSeedTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(EggSeedTests.__allTests__EggSeedTests)
    ]
  }
#endif
